pipeline {
    agent any

    environment {
        DB_HOST = 'db'
        DB_NAME = 'testdb'
        DB_USER = 'testuser'
        DB_PASS = 'testpass'
    }

    stages {
        stage('Clone repo') {
            steps {
                git 'https://github.com/iswwimm/aqa_070225.git'
            }
        }

        stage('Build Docker image') {
            steps {
                sh 'docker-compose build'
            }
        }

        stage('Start containers') {
            steps {
                sh 'docker-compose up -d'
                sh 'sleep 15' // wait for DB to be ready
            }
        }

        stage('Run tests') {
            steps {
                sh 'docker-compose run app python test_app.py'
            }
        }

        stage('Publish Results') {
            steps {
                junit 'test-results/*.xml' // якщо є JUnit, інакше можна лог в консоль
            }
        }
    }

    post {
        always {
            sh 'docker-compose down'
        }
        success {
            mail to: 'online@ithillel.ua',
                 subject: "SUCCESS: Build ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Good news! Build #${env.BUILD_NUMBER} succeeded."
        }
        failure {
            mail to: 'online@ithillel.ua',
                 subject: "FAILURE: Build ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Something went wrong with build #${env.BUILD_NUMBER}."
        }
    }
}
